name: Build RenPy APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: "21"
        distribution: "temurin"


    - name: Install Tools
      run: |
        sudo apt update
        sudo apt install -y ant unzip wget


    - name: Setup Android SDK
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools

        wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O sdk.zip

        unzip -q sdk.zip -d $HOME/android-sdk/cmdline-tools

        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV

        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

        yes | sdkmanager --licenses || true

        sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"



    - name: Find Game
      run: |
        if [ -f game/options.rpy ]; then
          echo "GAME_DIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV
        else
          echo "Game not found"
          exit 1
        fi



    - name: Download RenPy
      run: |
        wget -q https://www.renpy.org/dl/8.5.3/renpy-8.5.3-sdk.tar.bz2

        tar -xjf renpy-8.5.3-sdk.tar.bz2

        wget -q https://www.renpy.org/dl/8.5.3/renpy-8.5.3-rapt.zip

        unzip -q renpy-8.5.3-rapt.zip -d renpy-8.5.3-sdk



    - name: Prepare Android
      run: |
        cd "$GAME_DIR"

        keytool -genkeypair \
        -keystore android.keystore \
        -alias android \
        -keyalg RSA \
        -keysize 2048 \
        -validity 10000 \
        -storepass android \
        -keypass android \
        -dname "CN=RenPy"



    - name: Build APK
      run: |
        cd renpy-8.5.3-sdk

        ./renpy.sh launcher android_build "$GAME_DIR"



    - name: Find APK
      run: |
        find . -name "*.apk"



    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: renpy-apk
        path: "**/*.apk"
